-- database schema generated by ToolsApp (option 1), with modified FK names

drop table if exists "User" cascade;

drop table if exists "Watchdog" cascade;

drop table if exists "WatchdogAlert" cascade;

drop table if exists "WatchdogWebPage" cascade;

drop table if exists hibernate_unique_key cascade;

create table "User" (
    "Id" int8 not null,
   "Version" int8 not null,
   "Email" text not null,
   "PasswordHash" text not null,
   primary key ("Id")
);

create table "Watchdog" (
    "Id" int8 not null,
   "Version" int8 not null,
   "Name" text not null,
   primary key ("Id")
);

create table "WatchdogAlert" (
    "Id" int8 not null,
   "Version" int8 not null,
   "WatchdogId" int8 not null,
   "UserId" int8 not null,
   "SearchTerm" text,
   "SearchIntervalInSeconds" int4 not null,
   "Frequency" char(1) not null,
   primary key ("Id")
);

create table "WatchdogWebPage" (
    "Id" int8 not null,
   "Version" int8 not null,
   "Name" text,
   "Url" text not null,
   "Selector" text,
   "WatchdogId" int8,
   "Index" int4,
   primary key ("Id")
);

alter table "WatchdogAlert" 
    add constraint "FK_WatchdogAlert_Watchdog"
    foreign key ("WatchdogId") 
    references "Watchdog";

alter table "WatchdogAlert" 
    add constraint "FK_WatchdogAlert_User"
    foreign key ("UserId") 
    references "User";

alter table "WatchdogWebPage" 
    add constraint "FK_WatchdogWebPage_Watchdog" 
    foreign key ("WatchdogId") 
    references "Watchdog";

create table hibernate_unique_key (
     next_hi int8 
);

insert into hibernate_unique_key values ( 1 );
