<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CoreBackend.Tests</RootNamespace>
    <AssemblyName>CoreBackend.Tests</AssemblyName>
  </PropertyGroup>

  <Import Project="..\..\..\SharedAssemblyInfo.props" />

  <ItemGroup>
    <Compile Include="..\CoreBackend.TestsShared\GlobalUsings.cs" Link="GlobalUsings.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FakeItEasy" Version="9.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="NUnit" Version="4.5.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.1.0" />
    <PackageReference Include="Shouldly" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CoreBackend\CoreBackend.csproj" />
    <ProjectReference Include="..\CoreBackend.TestsShared\CoreBackend.TestsShared.csproj" />
  </ItemGroup>

</Project>
