//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrWatchdog.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrWatchdog.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create watchdog.
        /// </summary>
        public static string CreateWatchdog {
            get {
                return ResourceManager.GetString("CreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term to filter results.
        /// </summary>
        public static string FilterResults {
            get {
                return ResourceManager.GetString("FilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watchdogs.
        /// </summary>
        public static string ListOfWatchdogs {
            get {
                return ResourceManager.GetString("ListOfWatchdogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage watchdogs.
        /// </summary>
        public static string ManageWatchdogs {
            get {
                return ResourceManager.GetString("ManageWatchdogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr Watchdog.
        /// </summary>
        public static string MrWatchdog {
            get {
                return ResourceManager.GetString("MrWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string MyAlerts {
            get {
                return ResourceManager.GetString("MyAlerts", resourceCulture);
            }
        }
    }
}
