//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrWatchdog.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrWatchdog.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A watchdog for any publicly accessible web page.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Keep track of changes and get notified by email the moment a page updates or your search term appears.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    View public {0} or create your own scraper, and create a watchdog.
        ///&lt;/p&gt;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scrapers.
        /// </summary>
        public static string AboutScrapers {
            get {
                return ResourceManager.GetString("AboutScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new scraper {0}..
        /// </summary>
        public static string AddNewScraperRecommendation {
            get {
                return ResourceManager.GetString("AddNewScraperRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new watchdog, go to the list of {0}, select one, and choose &lt;i&gt;{1}&lt;/i&gt;..
        /// </summary>
        public static string AddNewWatchdogRecommendation {
            get {
                return ResourceManager.GetString("AddNewWatchdogRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add web page to scrape.
        /// </summary>
        public static string AddWebPageToScrape {
            get {
                return ResourceManager.GetString("AddWebPageToScrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated earnings for this month.
        /// </summary>
        public static string CalculatedEarningsForThisMonth {
            get {
                return ResourceManager.GetString("CalculatedEarningsForThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help? Contact support team at.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create scraper.
        /// </summary>
        public static string CreateScraper {
            get {
                return ResourceManager.GetString("CreateScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create watchdog.
        /// </summary>
        public static string CreateWatchdog {
            get {
                return ResourceManager.GetString("CreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete scraper.
        /// </summary>
        public static string DeleteScraper {
            get {
                return ResourceManager.GetString("DeleteScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete this scraper and all related user&apos;s watchdogs?.
        /// </summary>
        public static string DeleteScraperConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteScraperConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete watchdog.
        /// </summary>
        public static string DeleteWatchdog {
            get {
                return ResourceManager.GetString("DeleteWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete this watchdog?.
        /// </summary>
        public static string DeleteWatchdogConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteWatchdogConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete web page.
        /// </summary>
        public static string DeleteWebPage {
            get {
                return ResourceManager.GetString("DeleteWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid email address.
        /// </summary>
        public static string EmailAddressRegexAttribute {
            get {
                return ResourceManager.GetString("EmailAddressRegexAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable web page.
        /// </summary>
        public static string EnableWebPage {
            get {
                return ResourceManager.GetString("EnableWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error message.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally enter a search term to filter the results.
        /// </summary>
        public static string FilterResults {
            get {
                return ResourceManager.GetString("FilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to here.
        /// </summary>
        public static string Here {
            get {
                return ResourceManager.GetString("Here", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to home page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP headers (one per line; format: &quot;header name: value&quot;).
        /// </summary>
        public static string HttpHeaders {
            get {
                return ResourceManager.GetString("HttpHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTTP header format: &quot;{0}&quot;. Expected format is &quot;header name: value&quot;..
        /// </summary>
        public static string InvalidHttpHeaderFormatErrorTemplate {
            get {
                return ResourceManager.GetString("InvalidHttpHeaderFormatErrorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scrapers.
        /// </summary>
        public static string ListOfScrapers {
            get {
                return ResourceManager.GetString("ListOfScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login link sent.
        /// </summary>
        public static string LoginLinkSent {
            get {
                return ResourceManager.GetString("LoginLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A login link has been sent to your email &lt;span class=&quot;link-primary&quot;&gt;{0}&lt;/span&gt; . Check your email, and confirm the login by clicking the login link.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Waiting for the confirmation...
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;small&gt;
        ///        If you can&apos;t find the email, please check your spam folder and mark it as &lt;i&gt;Not Spam&lt;/i&gt; 
        ///        to ensure you receive future emails from {1}.
        ///    &lt;/small&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string LoginLinkSentDescription {
            get {
                return ResourceManager.GetString("LoginLinkSentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string LoginOr {
            get {
                return ResourceManager.GetString("LoginOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in / register.
        /// </summary>
        public static string LoginOrRegister {
            get {
                return ResourceManager.GetString("LoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register to create watchdog.
        /// </summary>
        public static string LoginOrRegisterToCreateWatchdog {
            get {
                return ResourceManager.GetString("LoginOrRegisterToCreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with email.
        /// </summary>
        public static string LoginWithEmail {
            get {
                return ResourceManager.GetString("LoginWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google.
        /// </summary>
        public static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make private.
        /// </summary>
        public static string MakePrivate {
            get {
                return ResourceManager.GetString("MakePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        public static string MakePublic {
            get {
                return ResourceManager.GetString("MakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really make the scraper private and non-discoverable by other users?.
        /// </summary>
        public static string MakeScraperPrivateConfirmationMessage {
            get {
                return ResourceManager.GetString("MakeScraperPrivateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really make the scraper public and discoverable by other users?.
        /// </summary>
        public static string MakeScraperPublicConfirmationMessage {
            get {
                return ResourceManager.GetString("MakeScraperPublicConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage scrapers created by other users..
        /// </summary>
        public static string ManageOtherUsersScrapersDescription {
            get {
                return ResourceManager.GetString("ManageOtherUsersScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageScraper {
            get {
                return ResourceManager.GetString("ManageScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage scrapers.
        /// </summary>
        public static string ManageScrapers {
            get {
                return ResourceManager.GetString("ManageScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage scrapers created by you..
        /// </summary>
        public static string ManageUserScrapersDescription {
            get {
                return ResourceManager.GetString("ManageUserScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr Watchdog.
        /// </summary>
        public static string MrWatchdog {
            get {
                return ResourceManager.GetString("MrWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My scraper.
        /// </summary>
        public static string MyScraper {
            get {
                return ResourceManager.GetString("MyScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My scrapers.
        /// </summary>
        public static string MyScrapers {
            get {
                return ResourceManager.GetString("MyScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your scrapers to create a watchdog..
        /// </summary>
        public static string MyScrapersDescription {
            get {
                return ResourceManager.GetString("MyScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You created this scraper.
        /// </summary>
        public static string MyScraperTooltip {
            get {
                return ResourceManager.GetString("MyScraperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My watchdogs.
        /// </summary>
        public static string MyWatchdogs {
            get {
                return ResourceManager.GetString("MyWatchdogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your watchdogs..
        /// </summary>
        public static string MyWatchdogsDescription {
            get {
                return ResourceManager.GetString("MyWatchdogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to the .
        /// </summary>
        public static string NavigateToThe {
            get {
                return ResourceManager.GetString("NavigateToThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scraped results are currently available..
        /// </summary>
        public static string NoScrapedResultsAvailable {
            get {
                return ResourceManager.GetString("NoScrapedResultsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scraped results matching the search term {0} are currently available..
        /// </summary>
        public static string NoScrapedResultsMatchingTheSearchTermAvailable {
            get {
                return ResourceManager.GetString("NoScrapedResultsMatchingTheSearchTermAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days between notifications for the same scraped result.
        /// </summary>
        public static string NumberOfDaysBetweenNotificationsForTheSameScrapedResult {
            get {
                return ResourceManager.GetString("NumberOfDaysBetweenNotificationsForTheSameScrapedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed scraping attempts before alerting by email.
        /// </summary>
        public static string NumberOfFailedScrapingAttemptsBeforeAlerting {
            get {
                return ResourceManager.GetString("NumberOfFailedScrapingAttemptsBeforeAlerting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users with a watchdog with email notification.
        /// </summary>
        public static string NumberOfUsersWithWatchdogWithEmailNotification {
            get {
                return ResourceManager.GetString("NumberOfUsersWithWatchdogWithEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of users with a watchdog without email notification.
        /// </summary>
        public static string NumberOfUsersWithWatchdogWithoutEmailNotification {
            get {
                return ResourceManager.GetString("NumberOfUsersWithWatchdogWithoutEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view this help anytime again..
        /// </summary>
        public static string OnboardingViewAgainStep {
            get {
                return ResourceManager.GetString("OnboardingViewAgainStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional localization JSON format: { &quot;en&quot;: &quot;English text&quot;, &quot;cs&quot;: &quot;Český text&quot; }.
        /// </summary>
        public static string OptionalLocalizationJsonFormat {
            get {
                return ResourceManager.GetString("OptionalLocalizationJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable it once your edits are complete so that watchdogs can continue watching it..
        /// </summary>
        public static string PleaseEnableItOnceYourEditsAreComplete {
            get {
                return ResourceManager.GetString("PleaseEnableItOnceYourEditsAreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string PrivateStatus {
            get {
                return ResourceManager.GetString("PrivateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scraper is private and not discoverable by other users..
        /// </summary>
        public static string PrivateStatusTooltip {
            get {
                return ResourceManager.GetString("PrivateStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public scrapers.
        /// </summary>
        public static string PublicScrapers {
            get {
                return ResourceManager.GetString("PublicScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse public scrapers to create a watchdog..
        /// </summary>
        public static string PublicScrapersDescription {
            get {
                return ResourceManager.GetString("PublicScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string PublicStatus {
            get {
                return ResourceManager.GetString("PublicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scraper is public and discoverable by other users..
        /// </summary>
        public static string PublicStatusTooltip {
            get {
                return ResourceManager.GetString("PublicStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be greater than or equal to {1}.
        /// </summary>
        public static string RangeAttribute {
            get {
                return ResourceManager.GetString("RangeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive email notification about new scraped results.
        /// </summary>
        public static string ReceiveEmailNotificationAboutNewResults {
            get {
                return ResourceManager.GetString("ReceiveEmailNotificationAboutNewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really remove the web page?.
        /// </summary>
        public static string RemoveWebPageConfirmationMessage {
            get {
                return ResourceManager.GetString("RemoveWebPageConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested to be made public.
        /// </summary>
        public static string RequestedToBeMadePublicStatus {
            get {
                return ResourceManager.GetString("RequestedToBeMadePublicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scraper has been requested to be made public and discoverable by other users..
        /// </summary>
        public static string RequestedToBeMadePublicStatusTooltip {
            get {
                return ResourceManager.GetString("RequestedToBeMadePublicStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request ID.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to make public.
        /// </summary>
        public static string RequestToMakePublic {
            get {
                return ResourceManager.GetString("RequestToMakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really request to make the scraper public and discoverable by other users?.
        /// </summary>
        public static string RequestToMakeScraperPublicConfirmationMessage {
            get {
                return ResourceManager.GetString("RequestToMakeScraperPublicConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraped on.
        /// </summary>
        public static string ScrapedOn {
            get {
                return ResourceManager.GetString("ScrapedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraped results.
        /// </summary>
        public static string ScrapedResults {
            get {
                return ResourceManager.GetString("ScrapedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraped results filtering not supported.
        /// </summary>
        public static string ScrapedResultsFilteringNotSupported {
            get {
                return ResourceManager.GetString("ScrapedResultsFilteringNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrape HTML as rendered by a browser.
        /// </summary>
        public static string ScrapeHtmlAsRenderedByBrowser {
            get {
                return ResourceManager.GetString("ScrapeHtmlAsRenderedByBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the scraper name. In the next step you will define web pages to scrape..
        /// </summary>
        public static string ScraperCreateOnboardingSetName {
            get {
                return ResourceManager.GetString("ScraperCreateOnboardingSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a web page this scraper will scrape..
        /// </summary>
        public static string ScraperDetailOnboardingAddWebPage {
            get {
                return ResourceManager.GetString("ScraperDetailOnboardingAddWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You navigated to a &lt;b&gt;scraper&lt;/b&gt; management.&lt;br/&gt;&lt;br/&gt;This scraper will scrape web pages and will select results based on the CSS selector..
        /// </summary>
        public static string ScraperDetailOnboardingIntro {
            get {
                return ResourceManager.GetString("ScraperDetailOnboardingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to make the scraper public and discoverable by other users who will then be able to create a watchdog with email notification about its new scraped results..
        /// </summary>
        public static string ScraperDetailOnboardingRequestToMakePublic {
            get {
                return ResourceManager.GetString("ScraperDetailOnboardingRequestToMakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can change the scraping interval..
        /// </summary>
        public static string ScraperDetailOnboardingScrapingInterval {
            get {
                return ResourceManager.GetString("ScraperDetailOnboardingScrapingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scraped results to be able to create a watchdog with an email notification about new scraped results..
        /// </summary>
        public static string ScraperDetailOnboardingViewScrapedResults {
            get {
                return ResourceManager.GetString("ScraperDetailOnboardingViewScrapedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The scraper earnings calculation will be based on the number of premium users having a watchdog for this scraper. The premium subscription is not yet implemented..
        /// </summary>
        public static string ScraperEarningsCalculationInfo {
            get {
                return ResourceManager.GetString("ScraperEarningsCalculationInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a watchdog with email notification about new scraped results or new scraped results matching the search term..
        /// </summary>
        public static string ScraperResultsOnboardingCreateWatchdog {
            get {
                return ResourceManager.GetString("ScraperResultsOnboardingCreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on a page showing &lt;b&gt;scraped results&lt;/b&gt; of a &lt;b&gt;scraper&lt;/b&gt;..
        /// </summary>
        public static string ScraperResultsOnboardingIntro {
            get {
                return ResourceManager.GetString("ScraperResultsOnboardingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register to create a watchdog with email notification about new scraped results or new scraped results matching the search term..
        /// </summary>
        public static string ScraperResultsOnboardingLoginOrRegisterToCreateWatchdog {
            get {
                return ResourceManager.GetString("ScraperResultsOnboardingLoginOrRegisterToCreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter a search term to filter the scraped results..
        /// </summary>
        public static string ScraperResultsOnboardingSearchTerm {
            get {
                return ResourceManager.GetString("ScraperResultsOnboardingSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scraper periodically scrapes web page(s) and selects scraped results from them..
        /// </summary>
        public static string ScraperResultsOnboardingWatchedWebPages {
            get {
                return ResourceManager.GetString("ScraperResultsOnboardingWatchedWebPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrapers.
        /// </summary>
        public static string Scrapers {
            get {
                return ResourceManager.GetString("Scrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrape web page.
        /// </summary>
        public static string ScrapeWebPage {
            get {
                return ResourceManager.GetString("ScrapeWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for.
        /// </summary>
        public static string ScrapingByBrowserWaitFor {
            get {
                return ResourceManager.GetString("ScrapingByBrowserWaitFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML loaded; images and CSS not loaded.
        /// </summary>
        public static string ScrapingByBrowserWaitForDomContentLoaded {
            get {
                return ResourceManager.GetString("ScrapingByBrowserWaitForDomContentLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML, images and CSS loaded.
        /// </summary>
        public static string ScrapingByBrowserWaitForLoad {
            get {
                return ResourceManager.GetString("ScrapingByBrowserWaitForLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML, images and CSS loaded; no network activity for 0.5 seconds; highest chance of all scripts to complete.
        /// </summary>
        public static string ScrapingByBrowserWaitForNetworkIdle {
            get {
                return ResourceManager.GetString("ScrapingByBrowserWaitForNetworkIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping interval in seconds.
        /// </summary>
        public static string ScrapingIntervalInSeconds {
            get {
                return ResourceManager.GetString("ScrapingIntervalInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS selector.
        /// </summary>
        public static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text instead of HTML.
        /// </summary>
        public static string SelectTextInsteadOfHtml {
            get {
                return ResourceManager.GetString("SelectTextInsteadOfHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status code.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute {
            get {
                return ResourceManager.GetString("StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no public scrapers..
        /// </summary>
        public static string ThereAreNoPublicScrapers {
            get {
                return ResourceManager.GetString("ThereAreNoPublicScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web page has been automatically disabled..
        /// </summary>
        public static string TheWebPageHasBeenAutomaticallyDisabled {
            get {
                return ResourceManager.GetString("TheWebPageHasBeenAutomaticallyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable it make sure the web page is successfully scraped..
        /// </summary>
        public static string ToEnableItMakeSureTheWebPageIsSuccessfullyScraped {
            get {
                return ResourceManager.GetString("ToEnableItMakeSureTheWebPageIsSuccessfullyScraped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid http or https web address..
        /// </summary>
        public static string UrlAttribute {
            get {
                return ResourceManager.GetString("UrlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scraped results.
        /// </summary>
        public static string ViewScrapedResults {
            get {
                return ResourceManager.GetString("ViewScrapedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You navigated to your &lt;b&gt;watchdog&lt;/b&gt;.&lt;br/&gt;
        ///&lt;br/&gt;
        ///This watchdog emails you notification about new results of the related scraper..
        /// </summary>
        public static string WatchdogOnboardingIntro {
            get {
                return ResourceManager.GetString("WatchdogOnboardingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It periodically watches related scraper results..
        /// </summary>
        public static string WatchdogOnboardingIntroScrapedResults {
            get {
                return ResourceManager.GetString("WatchdogOnboardingIntroScrapedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter a search term to filter the results. When no results, or no results matching the search term are currently available, you will receive an email notification as soon as they are available..
        /// </summary>
        public static string WatchdogOnboardingIntroSearchTerm {
            get {
                return ResourceManager.GetString("WatchdogOnboardingIntroSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    You can disable email notification about new results.
        ///&lt;/p&gt;
        ///&lt;div class=&quot;alert alert-info mb-3&quot;&gt;    
        ///    &lt;i class=&quot;fa-solid fa-circle-info&quot;&gt;&lt;/i&gt; Email notifications about new results are currently free.
        ///    In the future, free notifications about new results will be available only to a limited number of watchdogs without premium subscription.
        ///    The premium subscription is not yet implemented.
        ///&lt;/div&gt;.
        /// </summary>
        public static string WatchdogOnboardingReceiveNotification {
            get {
                return ResourceManager.GetString("WatchdogOnboardingReceiveNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched web pages.
        /// </summary>
        public static string WatchedWebPages {
            get {
                return ResourceManager.GetString("WatchedWebPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page not scraped yet.
        /// </summary>
        public static string WebPageNotScrapedYet {
            get {
                return ResourceManager.GetString("WebPageNotScrapedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can create a new scraper {0} and later make it public..
        /// </summary>
        public static string YouCanCreateScraperAndLaterMakeItPublic {
            get {
                return ResourceManager.GetString("YouCanCreateScraperAndLaterMakeItPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been logged in.
        /// </summary>
        public static string YouHaveBeenLoggedIn {
            get {
                return ResourceManager.GetString("YouHaveBeenLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    You&apos;ve been logged in on your original session. 
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;b&gt;Close this page&lt;/b&gt; and return to your original session.
        ///&lt;/p&gt;.
        /// </summary>
        public static string YouHaveBeenLoggedInDescription {
            get {
                return ResourceManager.GetString("YouHaveBeenLoggedInDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no scrapers created. You can create a scraper {0}..
        /// </summary>
        public static string YouHaveNoScrapersCreated {
            get {
                return ResourceManager.GetString("YouHaveNoScrapersCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no watchdogs..
        /// </summary>
        public static string YouHaveNoWatchdogs {
            get {
                return ResourceManager.GetString("YouHaveNoWatchdogs", resourceCulture);
            }
        }
    }
}
