//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MrWatchdog.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MrWatchdog.Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A watchdog platform for any publicly accessible web page on the internet.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Use it to watch any publicly accessible web page for changes and get notified by email when it changes or your search term is found.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    View existing public {0} and create a watchdog with email notification about new scraped results.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    {1} your own web scraper. {2} your existing web scrapers.
        ///&lt;/p&gt;.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string AboutCreate {
            get {
                return ResourceManager.GetString("AboutCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string AboutManage {
            get {
                return ResourceManager.GetString("AboutManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to web scrapers.
        /// </summary>
        public static string AboutWebScrapers {
            get {
                return ResourceManager.GetString("AboutWebScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add web page to scrape.
        /// </summary>
        public static string AddWebPageToScrape {
            get {
                return ResourceManager.GetString("AddWebPageToScrape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        public static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help? Contact our support team at.
        /// </summary>
        public static string ContactSupport {
            get {
                return ResourceManager.GetString("ContactSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create watchdog.
        /// </summary>
        public static string CreateWatchdog {
            get {
                return ResourceManager.GetString("CreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create web scraper.
        /// </summary>
        public static string CreateWebScraper {
            get {
                return ResourceManager.GetString("CreateWebScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete watchdog.
        /// </summary>
        public static string DeleteWatchdog {
            get {
                return ResourceManager.GetString("DeleteWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete this watchdog?.
        /// </summary>
        public static string DeleteWatchdogConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteWatchdogConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete web page.
        /// </summary>
        public static string DeleteWebPage {
            get {
                return ResourceManager.GetString("DeleteWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete web scraper.
        /// </summary>
        public static string DeleteWebScraper {
            get {
                return ResourceManager.GetString("DeleteWebScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete this web scraper and all of the user&apos;s watchdogs?.
        /// </summary>
        public static string DeleteWebScraperConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteWebScraperConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid email address.
        /// </summary>
        public static string EmailAddressRegexAttribute {
            get {
                return ResourceManager.GetString("EmailAddressRegexAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable web page.
        /// </summary>
        public static string EnableWebPage {
            get {
                return ResourceManager.GetString("EnableWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionally enter a search term to filter the results.
        /// </summary>
        public static string FilterResults {
            get {
                return ResourceManager.GetString("FilterResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP headers (one per line; format: &quot;header name: value&quot;).
        /// </summary>
        public static string HttpHeaders {
            get {
                return ResourceManager.GetString("HttpHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web scrapers.
        /// </summary>
        public static string ListOfWebScrapers {
            get {
                return ResourceManager.GetString("ListOfWebScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login link sent.
        /// </summary>
        public static string LoginLinkSent {
            get {
                return ResourceManager.GetString("LoginLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    A login link has been sent to your email &lt;span class=&quot;link-primary&quot;&gt;{0}&lt;/span&gt; . Check your email, and confirm the login by clicking the login link.
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    Waiting for the confirmation...
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;small&gt;
        ///        If you can&apos;t find the email, please check your spam folder and mark it as &lt;i&gt;Not Spam&lt;/i&gt; 
        ///        to ensure you receive future emails from {1}.
        ///    &lt;/small&gt;
        ///&lt;/p&gt;.
        /// </summary>
        public static string LoginLinkSentDescription {
            get {
                return ResourceManager.GetString("LoginLinkSentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string LoginOr {
            get {
                return ResourceManager.GetString("LoginOr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in / register.
        /// </summary>
        public static string LoginOrRegister {
            get {
                return ResourceManager.GetString("LoginOrRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register to create watchdog.
        /// </summary>
        public static string LoginOrRegisterToCreateWatchdog {
            get {
                return ResourceManager.GetString("LoginOrRegisterToCreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with email.
        /// </summary>
        public static string LoginWithEmail {
            get {
                return ResourceManager.GetString("LoginWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Google.
        /// </summary>
        public static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make private.
        /// </summary>
        public static string MakePrivate {
            get {
                return ResourceManager.GetString("MakePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make public.
        /// </summary>
        public static string MakePublic {
            get {
                return ResourceManager.GetString("MakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really make the web scraper private and non-discoverable by other users?.
        /// </summary>
        public static string MakeWebScraperPrivateConfirmationMessage {
            get {
                return ResourceManager.GetString("MakeWebScraperPrivateConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really make the web scraper public and discoverable by other users?.
        /// </summary>
        public static string MakeWebScraperPublicConfirmationMessage {
            get {
                return ResourceManager.GetString("MakeWebScraperPublicConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage web scrapers created by other users..
        /// </summary>
        public static string ManageOtherUsersWebScrapersDescription {
            get {
                return ResourceManager.GetString("ManageOtherUsersWebScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage web scrapers created by you..
        /// </summary>
        public static string ManageUserWebScrapersDescription {
            get {
                return ResourceManager.GetString("ManageUserWebScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string ManageWebScraper {
            get {
                return ResourceManager.GetString("ManageWebScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage web scrapers.
        /// </summary>
        public static string ManageWebScrapers {
            get {
                return ResourceManager.GetString("ManageWebScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr Watchdog.
        /// </summary>
        public static string MrWatchdog {
            get {
                return ResourceManager.GetString("MrWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My watchdogs.
        /// </summary>
        public static string MyWatchdogs {
            get {
                return ResourceManager.GetString("MyWatchdogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse your watchdogs..
        /// </summary>
        public static string MyWatchdogsDescription {
            get {
                return ResourceManager.GetString("MyWatchdogsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My web scraper.
        /// </summary>
        public static string MyWebScraper {
            get {
                return ResourceManager.GetString("MyWebScraper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My web scrapers.
        /// </summary>
        public static string MyWebScrapers {
            get {
                return ResourceManager.GetString("MyWebScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse web scrapers created by you..
        /// </summary>
        public static string MyWebScrapersDescription {
            get {
                return ResourceManager.GetString("MyWebScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You created this web scraper.
        /// </summary>
        public static string MyWebScraperTooltip {
            get {
                return ResourceManager.GetString("MyWebScraperTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need help?.
        /// </summary>
        public static string NeedHelp {
            get {
                return ResourceManager.GetString("NeedHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scraped results are currently available..
        /// </summary>
        public static string NoScrapedResultsAvailable {
            get {
                return ResourceManager.GetString("NoScrapedResultsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No scraped results matching the search term {0} are currently available..
        /// </summary>
        public static string NoScrapedResultsMatchingTheSearchTermAvailable {
            get {
                return ResourceManager.GetString("NoScrapedResultsMatchingTheSearchTermAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days between notifications for the same scraped result.
        /// </summary>
        public static string NumberOfDaysBetweenNotificationsForTheSameScrapedResult {
            get {
                return ResourceManager.GetString("NumberOfDaysBetweenNotificationsForTheSameScrapedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed scraping attempts before alerting by email.
        /// </summary>
        public static string NumberOfFailedScrapingAttemptsBeforeAlerting {
            get {
                return ResourceManager.GetString("NumberOfFailedScrapingAttemptsBeforeAlerting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view this help anytime again..
        /// </summary>
        public static string OnboardingViewAgainStep {
            get {
                return ResourceManager.GetString("OnboardingViewAgainStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    You can disable email notification about new scraped results.
        ///&lt;/p&gt;
        ///&lt;div class=&quot;alert alert-info mb-3&quot;&gt;    
        ///    &lt;i class=&quot;fa-solid fa-circle-info&quot;&gt;&lt;/i&gt; Email notifications about new scraped results are currently free.
        ///    In the future, this feature will be available only to premium subscribers.
        ///    The premium subscription is not yet implemented.
        ///&lt;/div&gt;.
        /// </summary>
        public static string OnboardingWatchdogReceiveNotificationStep {
            get {
                return ResourceManager.GetString("OnboardingWatchdogReceiveNotificationStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enable it once your edits are complete so that watchdogs can continue watching it..
        /// </summary>
        public static string PleaseEnableItOnceYourEditsAreComplete {
            get {
                return ResourceManager.GetString("PleaseEnableItOnceYourEditsAreComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string PrivateStatus {
            get {
                return ResourceManager.GetString("PrivateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web scraper is private and not discoverable by other users..
        /// </summary>
        public static string PrivateStatusTooltip {
            get {
                return ResourceManager.GetString("PrivateStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string PublicStatus {
            get {
                return ResourceManager.GetString("PublicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web scraper is public and discoverable by other users..
        /// </summary>
        public static string PublicStatusTooltip {
            get {
                return ResourceManager.GetString("PublicStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public web scrapers.
        /// </summary>
        public static string PublicWebScrapers {
            get {
                return ResourceManager.GetString("PublicWebScrapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse public web scrapers created by other users and you..
        /// </summary>
        public static string PublicWebScrapersDescription {
            get {
                return ResourceManager.GetString("PublicWebScrapersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be greater than or equal to {1}.
        /// </summary>
        public static string RangeAttribute {
            get {
                return ResourceManager.GetString("RangeAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive email notification about new scraped results.
        /// </summary>
        public static string ReceiveEmailNotificationAboutNewResults {
            get {
                return ResourceManager.GetString("ReceiveEmailNotificationAboutNewResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested to be made public.
        /// </summary>
        public static string RequestedToBeMadePublicStatus {
            get {
                return ResourceManager.GetString("RequestedToBeMadePublicStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web scraper has been requested to be made public and discoverable by other users..
        /// </summary>
        public static string RequestedToBeMadePublicStatusTooltip {
            get {
                return ResourceManager.GetString("RequestedToBeMadePublicStatusTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request to make public.
        /// </summary>
        public static string RequestToMakePublic {
            get {
                return ResourceManager.GetString("RequestToMakePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really request to make the web scraper public and discoverable by other users?.
        /// </summary>
        public static string RequestToMakeWebScraperPublicConfirmationMessage {
            get {
                return ResourceManager.GetString("RequestToMakeWebScraperPublicConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string RequiredAttribute {
            get {
                return ResourceManager.GetString("RequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraped on.
        /// </summary>
        public static string ScrapedOn {
            get {
                return ResourceManager.GetString("ScrapedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraped results.
        /// </summary>
        public static string ScrapedResults {
            get {
                return ResourceManager.GetString("ScrapedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrape web page.
        /// </summary>
        public static string ScrapeWebPage {
            get {
                return ResourceManager.GetString("ScrapeWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scraping interval in seconds.
        /// </summary>
        public static string ScrapingIntervalInSeconds {
            get {
                return ResourceManager.GetString("ScrapingIntervalInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSS selector.
        /// </summary>
        public static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select text instead of HTML.
        /// </summary>
        public static string SelectTextInsteadOfHtml {
            get {
                return ResourceManager.GetString("SelectTextInsteadOfHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string StringLengthAttribute {
            get {
                return ResourceManager.GetString("StringLengthAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web page has been automatically disabled..
        /// </summary>
        public static string TheWebPageHasBeenAutomaticallyDisabled {
            get {
                return ResourceManager.GetString("TheWebPageHasBeenAutomaticallyDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable it make sure the web page is successfully scraped..
        /// </summary>
        public static string ToEnableItMakeSureTheWebPageIsSuccessfullyScraped {
            get {
                return ResourceManager.GetString("ToEnableItMakeSureTheWebPageIsSuccessfullyScraped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid http or https web address..
        /// </summary>
        public static string UrlAttribute {
            get {
                return ResourceManager.GetString("UrlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View scraped results.
        /// </summary>
        public static string ViewScrapedResults {
            get {
                return ResourceManager.GetString("ViewScrapedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watched web pages.
        /// </summary>
        public static string WatchedWebPages {
            get {
                return ResourceManager.GetString("WatchedWebPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web page not scraped yet.
        /// </summary>
        public static string WebPageNotScrapedYet {
            get {
                return ResourceManager.GetString("WebPageNotScrapedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the web scraper name. In the next step you will define web pages to scrape..
        /// </summary>
        public static string WebScraperCreateOnboardingSetName {
            get {
                return ResourceManager.GetString("WebScraperCreateOnboardingSetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a watchdog with email notification about new scraped results or new scraped results matching the search term..
        /// </summary>
        public static string WebScraperResultsOnboardingCreateWatchdog {
            get {
                return ResourceManager.GetString("WebScraperResultsOnboardingCreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are on a page showing &lt;b&gt;scraped results&lt;/b&gt; of a web scraper..
        /// </summary>
        public static string WebScraperResultsOnboardingIntro {
            get {
                return ResourceManager.GetString("WebScraperResultsOnboardingIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in or register to create a watchdog with email notification about new scraped results or new scraped results matching the search term..
        /// </summary>
        public static string WebScraperResultsOnboardingLoginOrRegisterToCreateWatchdog {
            get {
                return ResourceManager.GetString("WebScraperResultsOnboardingLoginOrRegisterToCreateWatchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can enter a search term to filter the scraped results..
        /// </summary>
        public static string WebScraperResultsOnboardingSearchTerm {
            get {
                return ResourceManager.GetString("WebScraperResultsOnboardingSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This web scraper periodically scrapes web page(s) and selects scraped results from them..
        /// </summary>
        public static string WebScraperResultsOnboardingWatchedWebPages {
            get {
                return ResourceManager.GetString("WebScraperResultsOnboardingWatchedWebPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been logged in.
        /// </summary>
        public static string YouHaveBeenLoggedIn {
            get {
                return ResourceManager.GetString("YouHaveBeenLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;
        ///    You&apos;ve been logged in on your original session. 
        ///&lt;/p&gt;
        ///&lt;p&gt;
        ///    &lt;b&gt;Close this page&lt;/b&gt; and return to your original session.
        ///&lt;/p&gt;.
        /// </summary>
        public static string YouHaveBeenLoggedInDescription {
            get {
                return ResourceManager.GetString("YouHaveBeenLoggedInDescription", resourceCulture);
            }
        }
    }
}
