servers:
  web:
    - 192.168.0.190

proxy:
  hosts:
    - staging-local.mrwatchdog.com

env:
  clear:
    ASPNETCORE_ENVIRONMENT: "Staging"
    PlaywrightScraper__DisableWebPageSizeCheck: true
    PlaywrightScraper__SaveWebPageToTempDirectory: true

accessories:
  db:
    host: 192.168.0.190
  rabbitmq:
    host: 192.168.0.190
