# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine@sha256:d17d8d6511aee3dd54b4d9e8e03d867b1c3df28fb518ee9dd69e50305b7af4ee AS build
WORKDIR /app

# Install Node.js and npm
RUN apk add --no-cache nodejs npm

# Copy only project files first for better layer caching
COPY Core/*.csproj ./Core/
COPY Web/*.csproj ./Web/
COPY SharedAssemblyInfo.props .
RUN dotnet restore Web/Web.csproj

# Install Node packages
WORKDIR /app/Web
COPY Web/package*.json ./
RUN npm ci

# Copy the remaining source code
WORKDIR /app
COPY Core/. ./Core/
COPY Web/. ./Web/
RUN mkdir -p ./DatabaseScripts/ChangeScripts
COPY DatabaseScripts/ChangeScripts/. ./DatabaseScripts/ChangeScripts/

# Build front-end assets
WORKDIR /app/Web
RUN npx tsc --noEmit && node esbuild.config.js
WORKDIR /app

# Make sure the above is the same as for ../Dockerfile to be able to benefit from cached layers

# Copy only csproj files first
COPY MrWatchdog.sln .
COPY Core.Tests/*.csproj Core.Tests/
COPY TestsShared/*.csproj TestsShared/
COPY ToolsApp/*.csproj ToolsApp/
COPY Web.E2E.Tests/*.csproj Web.E2E.Tests/
COPY Web.Tests/*.csproj Web.Tests/

# Restore all projects (creates a cached layer)
RUN dotnet restore

# Copy test projects files
COPY Core.Tests/. ./Core.Tests/
COPY TestsShared/. ./TestsShared/
COPY ToolsApp/. ./ToolsApp/
COPY Web.E2E.Tests/. ./Web.E2E.Tests/
COPY Web.Tests/. ./Web.Tests/

RUN dotnet build

# ---- Runtime container: runs the tests ----
FROM mcr.microsoft.com/dotnet/sdk:10.0-alpine@sha256:d17d8d6511aee3dd54b4d9e8e03d867b1c3df28fb518ee9dd69e50305b7af4ee

# Install Alpine-native Chromium and Node.js (these are compiled for Apline's musl)
RUN apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont nodejs xvfb dbus mesa-gl

WORKDIR /app

# Tell Playwright to use system Node
ENV PLAYWRIGHT_NODEJS_PATH=/usr/bin/node
# This tells the .NET driver where the Alpine-native browser is
ENV PlaywrightScraper__BrowserExecutablePath=/usr/bin/chromium-browser

COPY --from=build /app .

# Copy NuGet packages cache
COPY --from=build /root/.nuget/packages /root/.nuget/packages

# Start Xvfb in the background to support headed Chrome browser and then run tests
ENTRYPOINT ["/bin/sh", "-c", "Xvfb :99 -screen 0 1920x1080x24 & export DISPLAY=:99 && dotnet test --no-restore --no-build"]
